### ISSUE TITLE
生成业务代码报错

### ISSUE THREAD

**Issue by linjiuqiu** [Deali-Axy/DjangoStarter#8]
使用代码生成器执行后提示以下错误, 哪个步骤错了吗
(my) D:\Users\a1848\PycharmProjects\DjangoStarter>python manage.py generate_code mgr_app 应用列表
2022-10-13 16:34:00,462 [D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\management\commands\generate_code.py:handle:32] [DEBUG] {'verbosity': 1, 'settings':
 None, 'pythonpath': None, 'traceback': False, 'no_color': False, 'force_color': False, 'skip_checks': False, 'app_label': ['mgr_app'], 'verbose_name': ['应用列表']}
2022-10-13 16:34:00,462 [D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\management\commands\generate_code.py:handle:37] [DEBUG] app_label=mgr_app, verbose=
应用列表
2022-10-13 16:34:00,462 [D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\analyzer.py:get_models:40] [DEBUG] Found django model: <DjangoModel>APP:应用列表:app

Load django app info finished. <DjangoApp>mgr_app:MgrApp:应用列表:[<DjangoModel>APP:应用列表:app]
2022-10-13 16:34:00,462 [D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\generator.py:__init__:21] [DEBUG] Generator init. django_app=<DjangoApp>mgr_app:MgrA
pp:应用列表:[<DjangoModel>APP:应用列表:app], template_path=D:\Users\a1848\PycharmProjects\DjangoStarter\contrib\code_generator\templates
2022-10-13 16:34:00,462 [D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\generator.py:_jinja2_to_py:31] [DEBUG] load jinja2 template: __init__.jinja2
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\management\commands\generate_code.py", line 46, in handle
    Generator(
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\generator.py", line 57, in make_all
    self.make_init()
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\generator.py", line 39, in make_init
    self._jinja2_to_py('__init__.jinja2', '__init__.py')
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\django_starter\contrib\code_generator\generator.py", line 32, in _jinja2_to_py
    template = self.jinja2_env.get_template(template_filename)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\Users\a1848\PycharmProjects\DjangoStarter\my\lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: __init__.jinja2

**Comment by Deali-Axy** [comment]
经检查是新架构的代码模板路径配置问题，新版本已修复~
